### ISSUE TITLE
Onyx Furnace and Dusts

### ISSUE THREAD

**Issue by BioMasterZap** [Sinhika/Machines#4]
This is on the 1.3.0.8 for 1.12, which may no longer be supported, but I didn't see it mentioned in the changelogs since then so it may still affect newer versions. I know in older versions the Onyx Furnace either didn't work on or have a chance to double ore dusts but it seems that isn't in the 1.12 version. This creates a potential dupe since many mods that let you crush ores to dust also let ingots be crushed back into dust.

Also, something else minor I noticed while testing this is that the tooltip for mousing over items doesn't appear in either the Mythril or Onyx Furnace.

**Comment by Sinhika** [comment]
I no longer maintain 1.12 versions. The Onyx Furnace has a chance of giving extra outputs; it's not guaranteed, so while you could stretch one ore out a lot with crushing/smelting/crushing/re-smelting cycles, it's not infinite--and you're still burning fuel every cycle.
